/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
      extend: {
          "colors": {
              "surface": "#fcf9f5",
              "on-primary-fixed-variant": "#474746",
              "on-background": "#1c1c1a",
              "secondary-fixed": "#e4e2dd",
              "surface-container": "#f0ede9",
              "on-surface": "#1c1c1a",
              "background": "#fcf9f5",
              "tertiary-fixed": "#e5e2db",
              "surface-container-high": "#eae8e4",
              "on-primary-container": "#858383",
              "primary-fixed": "#e5e2e1",
              "on-tertiary": "#ffffff",
              "tertiary-fixed-dim": "#c9c6c0",
              "on-error": "#ffffff",
              "tertiary": "#000000",
              "surface-container-low": "#f6f3ef",
              "on-primary": "#ffffff",
              "on-primary-fixed": "#1c1b1b",
              "error": "#ba1a1a",
              "outline-variant": "#c4c7c7",
              "surface-tint": "#5f5e5e",
              "on-secondary-fixed": "#1b1c19",
              "primary-container": "#1c1b1b",
              "inverse-on-surface": "#f3f0ec",
              "error-container": "#ffdad6",
              "tertiary-container": "#1c1c18",
              "inverse-primary": "#c8c6c5",
              "on-surface-variant": "#444748",
              "on-tertiary-container": "#85847e",
              "secondary-fixed-dim": "#c8c6c2",
              "on-secondary-container": "#63635f",
              "surface-dim": "#dcdad6",
              "surface-container-highest": "#e5e2de",
              "secondary": "#5e5e5b",
              "surface-bright": "#fcf9f5",
              "secondary-container": "#e1dfdb",
              "surface-container-lowest": "#ffffff",
              "on-tertiary-fixed": "#1c1c18",
              "inverse-surface": "#31302e",
              "on-error-container": "#93000a",
              "on-secondary-fixed-variant": "#474744",
              "primary-fixed-dim": "#c8c6c5",
              "primary": "#000000",
              "surface-variant": "#e5e2de",
              "on-tertiary-fixed-variant": "#474742",
              "on-secondary": "#ffffff",
              "outline": "#747878"
          },
          "borderRadius": {
              "DEFAULT": "0.125rem",
              "lg": "0.25rem",
              "xl": "0.5rem",
              "full": "0.75rem"
          },
          "spacing": {
              "unit": "8px",
              "margin-desktop": "48px",
              "stack-md": "16px",
              "gutter": "24px",
              "stack-lg": "32px",
              "stack-sm": "8px",
              "margin-mobile": "16px",
              "container-max": "1280px"
          },
          "fontFamily": {
              "body-lg": ["Hanken Grotesk"],
              "label-sm": ["Hanken Grotesk"],
              "display-lg": ["Newsreader"],
              "headline-md": ["Hanken Grotesk"],
              "headline-lg": ["Newsreader"],
              "body-md": ["Hanken Grotesk"],
              "headline-lg-mobile": ["Newsreader"]
          },
          "fontSize": {
              "body-lg": ["18px", {"lineHeight": "1.6", "fontWeight": "400"}],
              "label-sm": ["12px", {"lineHeight": "1", "letterSpacing": "0.05em", "fontWeight": "600"}],
              "display-lg": ["48px", {"lineHeight": "1.1", "letterSpacing": "-0.02em", "fontWeight": "600"}],
              "headline-md": ["20px", {"lineHeight": "1.4", "letterSpacing": "0.01em", "fontWeight": "700"}],
              "headline-lg": ["32px", {"lineHeight": "1.2", "fontWeight": "500"}],
              "body-md": ["16px", {"lineHeight": "1.6", "fontWeight": "400"}],
              "headline-lg-mobile": ["28px", {"lineHeight": "1.2", "fontWeight": "500"}]
          }
      },
  },
  plugins: [],
}
